name: CI Test Aanvraagverwerking

on:
  push:
    branches: [ main ]
    paths: [ 'Aanvraagverwerking/**' ]
  pull_request:
    paths: [ 'Aanvraagverwerking/**', '.github/workflows/ci.aanvraagverwerking.yml' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'

    - name: Download Go modules
      run: go mod tidy
      working-directory: ./Aanvraagverwerking

    - name: Run Go tests
      run: go test -v ./...
      working-directory: ./Aanvraagverwerking