name: CI Test ECD

on:
    push:
        branches: [ main ]
        paths:
            - 'ecd/**'
    pull_request:
        paths:
            - 'ecd/**'
    workflow_dispatch:

jobs:
  Run_Postman_Tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose -f 'ecd/compose.yaml' --env-file 'CI.env' up -d --build

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Wait for API to be ready
        run: |
            for i in {1..30}; do
            if curl -s http://127.0.0.1:8082/api/health; then
                echo "Service is up!"
                break
            fi
            echo "Waiting for service..."
            sleep 2
            done

      - name: Run Postman tests
        run: |
          newman run ecd/tests/ECD.tests.postman_collection.json

      - name: Tear down Docker Compose
        if: always()
        run: docker compose -f 'ecd/compose.yaml' down --remove-orphans --volumes