name: CI Test Product

on:
  push:
    branches: [ main ]
    paths: [ 'product/**' ]
  pull_request:
    paths: [ 'product/**', '.github/workflows/ci.product.yml' ]
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'

    - name: Download Go modules
      run: |
        go mod tidy
        go mod download
      working-directory: ./product

    - name: Run Go tests
      run: go test -v ./tests/...
      working-directory: ./product
