name: CI Test Recommendation

on:
  push:
    branches: [ main ]
    paths: [ 'recommendation/**' ]
  pull_request:
    paths: [ 'recommendation/**', '.github/workflows/ci.recommendation.yml' ]
  workflow_dispatch:  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4' 

    - name: Run Go tests
      run: go test -v ./recommendation/service/... 
