Resources:
  MyPostgresDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: my-postgres
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: ${{ secrets.postgres_user }}
      MasterUserPassword: ${{ secrets.postgres_pswd }}
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref MyDBSecurityGroup

  MyDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable RDS access from ECS
      VpcId: ${{ secrets.VPC_ID }}
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref ECSServiceSecurityGroup

  ECSServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS service access
      VpcId: ${{ secrets.VPC_ID }}
